name: app_update_manager
description: "A comprehensive Flutter package for managing app updates across Play Store, App Store, and custom backends with flexible update strategies."
version: 1.0.0
homepage: https://github.com/mixin27/app_update_manager

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  dio: ^5.9.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  workmanager: ^0.9.0+3

  # Android in-app updates
  in_app_update: ^4.2.5

  # Utilities
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
